# -*- coding: utf-8 -*-
"""live_detection_people_chairs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8TXRaOzuoOezxrF0pIWiabm3T2Bkbmw
"""

import cv2
from google.colab.patches import cv2_imshow  # Colab에서 이미지를 표시할 수 있도록 cv2_imshow 임포트
from ultralytics import solutions

# 이미지 경로 확인 후 읽기
image_path = "cafe.jpg"  # 이미지 경로 입력
im0 = cv2.imread(image_path)

# 이미지 경로가 잘못되었을 때 오류 메시지 출력
if im0 is None:
    raise FileNotFoundError(f"이미지 파일을 찾을 수 없습니다: {image_path}")

# 영역 설정 (여기서는 사각형 영역으로 설정)
region_points = [(20, 400), (1080, 400), (1080, 360), (20, 360)]  # 사각형 영역

# 객체 카운팅을 위한 초기화
counter = solutions.ObjectCounter(
    show=True,  # 결과 화면을 표시
    region=region_points,  # 영역 설정
    model="yolo11n.pt",  # YOLO 모델 사용 (필요에 따라 다른 모델 사용 가능)
    classes=[0, 56],  # 0: 사람 (person), 56: 의자 (chair)
)

# 객체 카운팅 적용
im0 = counter.count(im0)

# 결과 이미지 표시 (Colab 환경에서는 cv2_imshow 사용)
cv2_imshow(im0)  # cv2.imshow() 대신 사용

# 'q'를 누르면 종료
cv2.waitKey(0)
cv2.destroyAllWindows()

